# -*- coding: utf-8 -*-
"""R26 - generate the pure-CSS 3D model set (no libraries, no WebGL, no JS).

Everything is precomputed here: face normals, per-face lighting, and the exact
matrix3d / transform for every element, so the browser only ever animates one
composited transform per model (the scene rotation). Nothing else changes per
frame - that is what keeps it at 60fps.

Outputs
  docs/components/k3d.css   drop-in stylesheet (uses --ink/--line/--accent)
  docs/components/k3d.html  ready markup fragments, one block per model
  tools/k3d-preview.html    local demo (never deployed)
"""
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'docs', 'components')
MARK = '/* generated by tools/make-k3d.py -- do not hand-edit */'

# key light for the whole set: upper-left, slightly toward the viewer
LIGHTV = (-0.52, -0.74, 0.43)
_ln = math.sqrt(sum(c * c for c in LIGHTV))
LIGHT = tuple(c / _ln for c in LIGHTV)


def f(v):
    s = ('%.3f' % v).rstrip('0').rstrip('.')
    return '0' if s in ('', '-0') else s


def dot(a, b):
    return sum(x * y for x, y in zip(a, b))


def sub(a, b):
    return tuple(x - y for x, y in zip(a, b))


def norm(a):
    n = math.sqrt(sum(c * c for c in a)) or 1.0
    return tuple(c / n for c in a)


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def mix(c1, c2, t):
    return tuple(c1[i] + (c2[i] - c1[i]) * t for i in range(3))


def hexs(c):
    return '#%02x%02x%02x' % tuple(max(0, min(255, int(round(v)))) for v in c)


# palette stops are CSS variables so the day/night palette takes over
GLOSS = (242, 240, 236)
BODY = (150, 147, 140)
COAL = (96, 94, 90)


def shade(normal):
    """Lambert + a touch of rim: what a matte crystal facet would catch."""
    n = norm(normal)
    lam = max(0.0, dot(n, LIGHT))
    rim = max(0.0, dot(n, (-LIGHT[0], -LIGHT[1], abs(LIGHT[2])))) ** 3
    a = mix(COAL, BODY, 0.25 + 0.75 * lam)
    b = mix(a, GLOSS, 0.15 + 0.55 * lam + 0.25 * rim)
    return hexs(a), hexs(b), round(0.72 + 0.24 * lam, 3)


# ---------------------------------------------------------------- model 1
def crystal(scale=118.0):
    """Icosahedron: 20 real facets, each with its own baked lighting."""
    phi = (1 + math.sqrt(5)) / 2
    verts = []
    for s1 in (1, -1):
        for s2 in (1, -1):
            verts += [(s1, s2 * phi, 0), (0, s1, s2 * phi), (s1 * phi, 0, s2)]
    verts = [norm(v) for v in verts]
    # dedupe
    uniq = []
    for v in verts:
        if not any(sum((a - b) ** 2 for a, b in zip(v, u)) < 1e-9 for u in uniq):
            uniq.append(v)
    verts = uniq
    # the true edge length: the shortest distance anywhere in the vertex set.
    # (triangles built from the longer spacing are not faces - they cut through
    #  the solid, and were what made the first pass emit 40 "faces".)
    emin = min(math.sqrt(sum((x - y) ** 2 for x, y in zip(verts[i], verts[j])))
               for i in range(len(verts)) for j in range(i + 1, len(verts)))
    edge_len = emin * emin
    faces = []
    n = len(verts)
    for i in range(n):
        for j in range(i + 1, n):
            for k in range(j + 1, n):
                a, b, c = verts[i], verts[j], verts[k]
                d1 = sum((x - y) ** 2 for x, y in zip(a, b))
                d2 = sum((x - y) ** 2 for x, y in zip(b, c))
                d3 = sum((x - y) ** 2 for x, y in zip(c, a))
                if (abs(d1 - edge_len) < 1e-9 and abs(d2 - edge_len) < 1e-9
                        and abs(d3 - edge_len) < 1e-9):
                    cen = tuple((a[m] + b[m] + c[m]) / 3 for m in range(3))
                    nv = cross(sub(b, a), sub(c, a))
                    if dot(nv, cen) < 0:
                        b, c = c, b
                        nv = cross(sub(b, a), sub(c, a))
                    faces.append((a, b, c, nv))
    assert len(faces) == 20, 'icosahedron must have 20 faces, got %d' % len(faces)
    css, html = [], []
    for idx, (a, b, c, nv) in enumerate(faces):
        A = tuple(v * scale for v in a)
        B = tuple(v * scale for v in b)
        Cc = tuple(v * scale for v in c)
        u = tuple(x / 100.0 for x in sub(B, A))      # local x basis (100px box)
        v2 = tuple(x / 100.0 for x in sub(Cc, A))    # local y basis
        w = norm(nv)
        m = (u[0], u[1], u[2], 0, v2[0], v2[1], v2[2], 0,
             w[0], w[1], w[2], 0, A[0], A[1], A[2], 1)
        c1, c2, op = shade(nv)
        css.append('.k3d--crystal .f%d {' % idx)
        css.append('  transform: matrix3d(%s);' % ','.join(f(x) for x in m))
        css.append('  background: linear-gradient(155deg, %s, %s);' % (c1, c2))
        css.append('  opacity: %s;' % f(op))
        css.append('}')
        html.append('<i class="f%d"></i>' % idx)
    return '\n'.join(css), '\n'.join(html)


# ---------------------------------------------------------------- model 2
def torus(rings=44, major=112.0, minor=27.0):
    css, html = [], []
    for i in range(rings):
        deg = 360.0 * i / rings
        rad = math.radians(deg)
        # facing depth drives opacity: rings at the back recede
        depth = (math.cos(rad) + 1) / 2
        css.append('.k3d--torus .r%d {' % i)
        css.append('  transform: rotateZ(%sdeg) translateX(%spx) rotateY(90deg);'
                   % (f(deg), f(major)))
        css.append('  width: %spx; height: %spx;' % (f(2 * minor), f(2 * minor)))
        css.append('  opacity: %s;' % f(0.28 + 0.62 * depth))
        css.append('}')
        html.append('<i class="r%d"></i>' % i)
    return '\n'.join(css), '\n'.join(html)


# ---------------------------------------------------------------- model 3
def cube(a=92.0):
    css, html = [], []
    # six translucent panels
    for i, tr in enumerate([
            'translateZ(%spx)' % f(a),
            'rotateY(180deg) translateZ(%spx)' % f(a),
            'rotateY(90deg) translateZ(%spx)' % f(a),
            'rotateY(-90deg) translateZ(%spx)' % f(a),
            'rotateX(90deg) translateZ(%spx)' % f(a),
            'rotateX(-90deg) translateZ(%spx)' % f(a)]):
        css.append('.k3d--cube .p%d { transform: %s; }' % (i, tr))
        html.append('<i class="p%d"></i>' % i)
    # twelve edges
    e = 0
    for sy in (1, -1):
        for sz in (1, -1):
            css.append('.k3d--cube .e%d { transform: translate3d(0,%spx,%spx); '
                       'width:%spx; }' % (e, f(sy * a), f(sz * a), f(2 * a)))
            html.append('<i class="e%d"></i>' % e)
            e += 1
    for sx in (1, -1):
        for sz in (1, -1):
            css.append('.k3d--cube .e%d { transform: translate3d(%spx,0,%spx) '
                       'rotateZ(90deg); width:%spx; }'
                       % (e, f(sx * a), f(sz * a), f(2 * a)))
            html.append('<i class="e%d"></i>' % e)
            e += 1
    for sx in (1, -1):
        for sy in (1, -1):
            css.append('.k3d--cube .e%d { transform: translate3d(%spx,%spx,0) '
                       'rotateY(90deg); width:%spx; }'
                       % (e, f(sx * a), f(sy * a), f(2 * a)))
            html.append('<i class="e%d"></i>' % e)
            e += 1
    # eight vertices
    v = 0
    for sx in (1, -1):
        for sy in (1, -1):
            for sz in (1, -1):
                css.append('.k3d--cube .v%d { transform: translate3d(%spx,%spx,%spx); }'
                           % (v, f(sx * a), f(sy * a), f(sz * a)))
                html.append('<i class="v%d"></i>' % v)
                v += 1
    return '\n'.join(css), '\n'.join(html)


# ---------------------------------------------------------------- model 4
def helix(steps=34, radius=74.0, height=210.0):
    css, html = [], []
    idx = 0
    for strand in (0, 1):
        for i in range(steps):
            t = i / float(steps - 1)
            deg = 360.0 * t * 1.6 + strand * 180.0
            y = -height / 2 + height * t
            rad = math.radians(deg)
            depth = (math.sin(rad) + 1) / 2
            css.append('.k3d--helix .s%d {' % idx)
            css.append('  transform: translateY(%spx) rotateY(%sdeg) '
                       'translateX(%spx) rotateZ(-16deg);'
                       % (f(y), f(deg), f(radius)))
            css.append('  opacity: %s;' % f(0.4 + 0.55 * depth))
            css.append('}')
            html.append('<i class="s%d"></i>' % idx)
            idx += 1
    return '\n'.join(css), '\n'.join(html)


BASE_CSS = """
.k3d { --k3d-size: 260px; position: relative; display: block;
       width: var(--k3d-size); height: var(--k3d-size);
       perspective: 1100px; perspective-origin: 50% 42%; }
.k3d-scene { position: absolute; inset: 0; transform-style: preserve-3d;
             animation: k3d-turn var(--k3d-dur, 28s) linear infinite; }
.k3d-scene > i { position: absolute; left: 50%; top: 50%; display: block;
                 transform-style: preserve-3d; }

/* 1 - crystal: solid facets, each pre-lit */
.k3d--crystal .k3d-scene > i { width: 100px; height: 100px; margin: 0;
  transform-origin: 0 0; clip-path: polygon(0 0, 100% 0, 0 100%);
  backface-visibility: hidden; }
.k3d--crystal { --k3d-dur: 30s; }

/* 2 - torus: hairline rings, depth-faded */
.k3d--torus .k3d-scene > i { margin: 0; border-radius: 50%;
  border: 1px solid var(--accent, #9e2b25); transform-origin: 50% 50%;
  margin-left: -0.5px; box-sizing: border-box; }
.k3d--torus { --k3d-dur: 38s; }

/* 3 - cube: glass panels + wireframe + vertex nodes */
.k3d--cube .k3d-scene > i.p { width: 184px; height: 184px; margin: -92px 0 0 -92px;
  background: linear-gradient(140deg, rgba(255,255,255,0.16), rgba(120,118,114,0.06));
  border: 1px solid var(--line, #c9c7c2); }
.k3d--cube .k3d-scene > i.e { height: 1px; margin: 0 0 0 -92px;
  background: linear-gradient(90deg, var(--ink, #9a9894), var(--accent, #9e2b25)); }
.k3d--cube .k3d-scene > i.v { width: 7px; height: 7px; margin: -3.5px 0 0 -3.5px;
  border-radius: 50%; background: var(--accent, #9e2b25); }
.k3d--cube { --k3d-dur: 24s; }

/* 4 - helix: two strands of thin plates */
.k3d--helix .k3d-scene > i { width: 54px; height: 4px; margin: -2px 0 0 -27px;
  border-radius: 2px;
  background: linear-gradient(90deg, var(--ink, #9a9894), var(--accent, #9e2b25)); }
.k3d--helix { --k3d-dur: 34s; }

@keyframes k3d-turn {
  from { transform: rotateX(-16deg) rotateY(0deg); }
  to   { transform: rotateX(-16deg) rotateY(360deg); }
}
@media (prefers-reduced-motion: reduce) {
  .k3d-scene { animation: none; transform: rotateX(-16deg) rotateY(-34deg); }
}
"""

MODELS = [('crystal', crystal), ('torus', torus), ('cube', cube), ('helix', helix)]


def main():
    os.makedirs(OUT, exist_ok=True)
    css_parts = [MARK, BASE_CSS]
    blocks = []
    for name, fn in MODELS:
        css, html = fn()
        css_parts.append('\n/* ---- %s ---- */\n%s\n' % (name, css))
        blocks.append((name, html))
    open(os.path.join(OUT, 'k3d.css'), 'w', encoding='utf-8', newline='\n').write(
        '\n'.join(css_parts))

    frag = [MARK.replace('/*', '<!--', 1).replace('*/', ' -->', 1)]
    frag.append('<!-- copy one block into a page; it needs k3d.css -->')
    for name, html in blocks:
        frag.append('\n<!-- %s -->\n<div class="k3d k3d--%s" aria-hidden="true">\n'
                    '  <div class="k3d-scene">\n%s\n  </div>\n</div>'
                    % (name, name, html))
    frag_text = '\n'.join(frag)
    open(os.path.join(OUT, 'k3d.html'), 'w', encoding='utf-8', newline='\n').write(
        frag_text + '\n')

    demo = """<!doctype html>
<!-- R26 local demo of the CSS 3D models. tools/ only - never deployed. -->
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>R26 · CSS 3D 模型</title>
<link rel="stylesheet" href="../docs/components/k3d.css">
<style>
  :root { --bg: #e4e2df; --panel: #ebe9e6; --ink: #3b3a38; --muted: #8b8985;
          --line: #c9c7c2; --accent: #9e2b25; }
  html[data-theme="dark"] { --bg: #121110; --panel: #1c1a18; --ink: #ebe9e5;
          --muted: #a3a09a; --line: #3c3a36; --accent: #d4604f; }
  body { margin: 0; padding: 34px 24px 60px; background: var(--bg); color: var(--ink);
         font-family: Georgia, "Songti SC", serif; }
  .wrap { max-width: 1080px; margin: 0 auto; }
  .top { display: flex; align-items: baseline; gap: 16px; border-bottom: 1px solid
         var(--line); padding-bottom: 12px; }
  h1 { font-size: 19px; font-weight: normal; letter-spacing: 0.06em; margin: 0; }
  .sub { font-family: ui-monospace, Consolas, monospace; font-size: 10.5px;
         letter-spacing: 0.22em; color: var(--muted); }
  .btn { margin-left: auto; background: none; border: 1px solid var(--line);
         color: var(--muted); font-family: ui-monospace, Consolas, monospace;
         font-size: 10.5px; letter-spacing: 0.2em; padding: 7px 13px; cursor: pointer; }
  .btn:hover { color: var(--accent); border-color: var(--accent); }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
          gap: 22px; margin-top: 26px; }
  .cell { border: 1px solid var(--line); background: var(--panel); padding: 18px 0 10px; }
  .cell h2 { margin: 14px 0 2px; font-size: 13.5px; font-weight: normal;
             text-align: center; letter-spacing: 0.05em; }
  .cell .en { font-family: ui-monospace, Consolas, monospace; font-size: 9px;
              letter-spacing: 0.2em; color: var(--muted); text-align: center; }
  .k3d { margin: 0 auto; }
  .note { margin-top: 34px; font-size: 12.5px; line-height: 2; color: var(--muted); }
</style>
</head>
<body>
<div class="wrap">
  <div class="top">
    <h1>R26 · 3D 模型（纯 CSS，无库无 JS）</h1>
    <span class="sub">CSS 3D / GPU COMPOSITED</span>
    <button class="btn" id="themeBtn">切换夜间 / NIGHT</button>
  </div>
  <div class="grid">
__CELLS__
  </div>
  <p class="note">
    每个模型只有一个动画属性在跑：场景的 rotateY（合成层，不触发重排/重绘）。面片朝向、法线光照、
    深度淡出全部在生成期烘焙成 matrix3d 与渐变，运行时零计算。<br>
    <code>prefers-reduced-motion: reduce</code> 时整体静止在一个构图角度（这些是真实页面里的内联 DOM，
    媒体查询能生效，不像 &lt;img&gt; 里的 SVG）。<br>
    引入方式：把 <code>docs/components/k3d.css</code> 挂上，再从 <code>docs/components/k3d.html</code>
    拷一个 <code>&lt;div class="k3d k3d--xxx"&gt;</code> 块即可；配色跟随 <code>--ink / --line / --accent</code>。
  </p>
</div>
<script>
document.getElementById('themeBtn').onclick = () => {
  const d = document.documentElement;
  d.dataset.theme = d.dataset.theme === 'dark' ? 'light' : 'dark';
};
</script>
</body>
</html>
"""
    cells = []
    names = {'crystal': '晶体二十面体 / CRYSTAL', 'torus': '环面线圈 / TORUS',
             'cube': '玻璃立方 / CUBE', 'helix': '双螺旋 / HELIX'}
    for name, html in blocks:
        zh, en = names[name].split(' / ')
        cells.append('    <div class="cell">\n'
                     '      <div class="k3d k3d--%s" aria-hidden="true">\n'
                     '        <div class="k3d-scene">\n%s\n        </div>\n'
                     '      </div>\n'
                     '      <h2>%s</h2>\n      <div class="en">%s</div>\n'
                     '    </div>' % (name, html, zh, en))
    demo = demo.replace('__CELLS__', '\n'.join(cells))
    open(os.path.join(ROOT, 'tools', 'k3d-preview.html'), 'w', encoding='utf-8',
         newline='\n').write(demo)
    print('wrote docs/components/k3d.css, k3d.html and tools/k3d-preview.html')


if __name__ == '__main__':
    main()
