# -*- coding: utf-8 -*-
"""R25 - refine the decorative line-art set (light + pre-baked dark variants).

Pure stdlib, no dependencies. Every design is generated twice: once with the
day palette, once with the night palette (never a runtime filter invert).

  deco_armillary[_dark]   - armillary sphere: layered rings, metal gradient,
                            graduation, rivets, specular arc, and slow
                            differential rotation (rings + orbiting markers)
  deco_bloom[_dark]       - seed-of-life core, noise stripped down to the
                            necessary overlapping circles
  deco_phases[_dark]      - moon phases with shading gradient, surface texture,
                            rim light, sequence scale, and a real synodic cycle
  deco_resonance[_dark]   - interference rose (unchanged)
  deco_rosette[_dark]     - rose window skeleton only: frame + mullions + petals

Animation contract: only `transform` and `opacity` animate, nothing else; every
element carries a static base transform/opacity so the reduced-motion frame is
exactly the composed still, and `@media (prefers-reduced-motion: reduce)` kills
the animations. No JS anywhere.

Safety: an existing file is overwritten only if it carries this generator's
marker comment, so no hand-made asset can ever be clobbered.
"""
import math
import os
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'docs', 'assets')
S = 800
C = 400.0
MARK = '<!-- generated by tools/make-deco-lineart.py -->'

# the key light shared by every design: upper-left, so nothing looks locally lit
LIGHT_DEG = -58.0

LIGHT = dict(ink='#9a9894', soft='#b8b5b0', faint='#cfccc7',
             accent='#9e2b25', wash='#9a9894', gloss='#f2f0ec',
             coal='#7f7d79', shadow='#9a9894', bounce='#c6c3be',
             band='0.5',
             metal=('#5f5d5a', '#9d9a95', '#75736f', '#c2bfba',
                    '#847f7b', '#d6d3ce', '#6b6965'))
DARK = dict(ink='#b6b3ad', soft='#7e7b75', faint='#4c4a46',
            accent='#d4604f', wash='#b6b3ad', gloss='#f4f2ee',
            coal='#6f6d69', shadow='#2b2926', bounce='#6d6a66',
            band='0.55',
            metal=('#4a4845', '#8b8883', '#534f4c', '#adaaa4',
                   '#5e5b57', '#c4c1bb', '#474541'))

T_MOON = 48.0   # seconds for one full synodic cycle of every moon


def f(v):
    s = ('%.2f' % v).rstrip('0').rstrip('.')
    return '0' if s in ('', '-0') else s


# ---------------------------------------------------------------- helpers
def circle(r, col, w=1.0, dash=None, fill='none', cx=C, cy=C, op=None):
    d = ' stroke-dasharray="%s"' % dash if dash else ''
    o = ' opacity="%s"' % op if op else ''
    return ('<circle cx="%s" cy="%s" r="%s" fill="%s" stroke="%s" '
            'stroke-width="%s"%s%s/>' % (f(cx), f(cy), f(r), fill, col, f(w), d, o))


def line(x1, y1, x2, y2, col, w=1.0, dash=None, op=None):
    d = ' stroke-dasharray="%s"' % dash if dash else ''
    o = ' opacity="%s"' % op if op else ''
    return ('<line x1="%s" y1="%s" x2="%s" y2="%s" stroke="%s" '
            'stroke-width="%s"%s%s/>' % (f(x1), f(y1), f(x2), f(y2), col, f(w), d, o))


def path(d, col, w=1.0, dash=None, fill='none', op=None, fill_op=None, cls=None,
         style=None):
    dd = ' stroke-dasharray="%s"' % dash if dash else ''
    o = ' opacity="%s"' % op if op else ''
    fo = ' fill-opacity="%s"' % fill_op if fill_op else ''
    c = ' class="%s"' % cls if cls else ''
    s = ' style="%s"' % style if style else ''
    return ('<path%s d="%s" fill="%s"%s stroke="%s" stroke-width="%s"%s%s%s/>'
            % (c, d, fill, fo, col, f(w), dd, o, s))


def ellipse(rx, ry, col, w=1.0, dash=None, cx=C, cy=C, op=None):
    d = ' stroke-dasharray="%s"' % dash if dash else ''
    o = ' opacity="%s"' % op if op else ''
    return ('<ellipse cx="%s" cy="%s" rx="%s" ry="%s" fill="none" stroke="%s" '
            'stroke-width="%s"%s%s/>' % (f(cx), f(cy), f(rx), f(ry), col, f(w), d, o))


def polyline(pts, col, w=1.0, close=False, dash=None, op=None):
    d = 'M ' + ' L '.join('%s %s' % (f(x), f(y)) for x, y in pts)
    if close:
        d += ' Z'
    return path(d, col, w, dash=dash, op=op)


def reg(n, r, cx=C, cy=C, off=0.0):
    return [(cx + r * math.cos(math.radians(off + i * 360.0 / n)),
             cy + r * math.sin(math.radians(off + i * 360.0 / n))) for i in range(n)]


def text(x, y, s, col, size=13, anchor='middle', ls=1.2, op=None):
    o = ' opacity="%s"' % op if op else ''
    return ('<text x="%s" y="%s" text-anchor="%s" font-family="Menlo, Consolas, '
            'monospace" font-size="%s" letter-spacing="%s" fill="%s"%s>%s</text>'
            % (f(x), f(y), anchor, f(size), f(ls), col, o, s))


def arc(cx, cy, r, a0, a1, sweep=1):
    """Hairline arc between two angles (degrees, screen space)."""
    p0 = (cx + r * math.cos(math.radians(a0)), cy + r * math.sin(math.radians(a0)))
    p1 = (cx + r * math.cos(math.radians(a1)), cy + r * math.sin(math.radians(a1)))
    return 'M %s %s A %s %s 0 0 %d %s %s' % (f(p0[0]), f(p0[1]), f(r), f(r),
                                             sweep, f(p1[0]), f(p1[1]))


def lcg(seed):
    s = seed
    while True:
        s = (1103515245 * s + 12345) % (1 << 31)
        yield s / float(1 << 31)


# ---------------------------------------------------------------- materials
def light_grad(p, ident='k-light', deg=LIGHT_DEG):
    """One key light for the entire drawing - every stroke reads the same source."""
    rad = math.radians(deg)
    x1 = C - 520 * math.cos(rad)
    y1 = C - 520 * math.sin(rad)
    x2 = C + 520 * math.cos(rad)
    y2 = C + 520 * math.sin(rad)
    return ('<linearGradient id="%s" gradientUnits="userSpaceOnUse" '
            'x1="%s" y1="%s" x2="%s" y2="%s">'
            '<stop offset="0" stop-color="%s"/>'
            '<stop offset="0.44" stop-color="%s"/>'
            '<stop offset="0.68" stop-color="%s"/>'
            '<stop offset="1" stop-color="%s"/></linearGradient>'
            % (ident, f(x1), f(y1), f(x2), f(y2),
               p['gloss'], p['ink'], p['coal'], p['bounce']))


def metal_grad(p, ident, deg=LIGHT_DEG + 96.0):
    """Brushed metal: many short stops across one shared light direction."""
    rad = math.radians(deg)
    x1 = C - 560 * math.cos(rad)
    y1 = C - 560 * math.sin(rad)
    x2 = C + 560 * math.cos(rad)
    y2 = C + 560 * math.sin(rad)
    stops = ''.join('<stop offset="%s" stop-color="%s"/>'
                    % (f(i / (len(p['metal']) - 1.0)), c)
                    for i, c in enumerate(p['metal']))
    return ('<linearGradient id="%s" gradientUnits="userSpaceOnUse" '
            'x1="%s" y1="%s" x2="%s" y2="%s">%s</linearGradient>'
            % (ident, f(x1), f(y1), f(x2), f(y2), stops))


def lit_line(p, r, w=1.0, dash=None, op=None, cx=C, cy=C):
    """Hairline plus its own directional pass: a wire that knows the light."""
    return (circle(r, p['ink'], w, dash=dash, cx=cx, cy=cy, op=op)
            + circle(r, 'url(#k-light)', max(w + 1.2, 1.7), dash=dash, cx=cx, cy=cy,
                     op=f(0.42 * float(op or 1))))


def band_ring(p, r, w, ident=None, op=None):
    """Thick metal band: gradient body + key edge lit + shadow edge coal."""
    stroke = 'url(#%s)' % ident if ident else p['ink']
    out = '<circle cx="%s" cy="%s" r="%s" fill="none" stroke="%s" stroke-width="%s" opacity="%s"/>' % (
        f(C), f(C), f(r), stroke, f(w), op or p['band'])
    out += path(arc(C, C, r + w / 2.0 - 0.4, LIGHT_DEG - 96, LIGHT_DEG + 96),
                p['gloss'], 0.9, op='0.7')
    out += path(arc(C, C, r - w / 2.0 + 0.4, LIGHT_DEG + 84, LIGHT_DEG + 276),
                p['coal'], 0.85, op='0.55')
    return out


def stipple(p, cx, cy, r0, r1, n, seed=7, size=0.62, op=0.22):
    """Deterministic micro grain - real texture without a single pixel filter."""
    g = lcg(seed)
    alpha = f(float(op))
    out = []
    for _ in range(n):
        a = g.__next__() * 2 * math.pi
        rr = r0 + (r1 - r0) * math.sqrt(g.__next__())
        out.append(circle(size, p['coal'], 0, cx=cx + rr * math.cos(a),
                          cy=cy + rr * math.sin(a), fill=p['coal'], op=alpha))
    return ''.join(out)


# ---------------------------------------------------------------- motion css
ANIM_BASE = """
    /* only transform + opacity ever animate; no layout, no paint churn */
    .k-anim { transform-box: view-box; animation-iteration-count: infinite;
              animation-timing-function: linear; animation-delay: 0s; }
"""

MOON_CSS = ANIM_BASE + """
    .k-anim { animation-duration: %ss; }
    .k-core-b { animation-name: koyo-mod, koyo-erase; }
    .k-pen-b  { animation-name: koyo-mod-pen, koyo-erase; }
    .k-core-w { animation-name: koyo-mod, koyo-add; }
    .k-pen-w  { animation-name: koyo-mod-pen, koyo-add; }
    .k-term   { animation-name: koyo-mod; }
    .k-pen-t  { animation-name: koyo-mod-pen; }
    @keyframes koyo-mod {
        0%%    { transform: scaleX(1); }
        12.5%% { transform: scaleX(0.70711); }
        25%%   { transform: scaleX(0); }
        37.5%% { transform: scaleX(-0.70711); }
        50%%   { transform: scaleX(-1); }
        62.5%% { transform: scaleX(-0.70711); }
        75%%   { transform: scaleX(0); }
        87.5%% { transform: scaleX(0.70711); }
        100%%  { transform: scaleX(1); }
    }
    @keyframes koyo-erase { 0%%,24.6%% { opacity:1 } 25.4%%,74.6%% { opacity:0 } 75.4%%,100%% { opacity:1 } }
    @keyframes koyo-add   { 0%%,24.6%% { opacity:0 } 25.4%%,74.6%% { opacity:1 } 75.4%%,100%% { opacity:0 } }
    /* the penumbra: Earth's shadow is soft, so its edge trails the terminator
       by a hair - same cycle, slightly smaller sweep, lower alpha */
    @keyframes koyo-mod-pen {
        0%%    { transform: scaleX(1.06); }
        12.5%% { transform: scaleX(0.74954); }
        25%%   { transform: scaleX(0); }
        37.5%% { transform: scaleX(-0.74954); }
        50%%   { transform: scaleX(-1.06); }
        62.5%% { transform: scaleX(-0.74954); }
        75%%   { transform: scaleX(0); }
        87.5%% { transform: scaleX(0.74954); }
        100%%  { transform: scaleX(1.06); }
    }
""" % f(T_MOON)


RM_RULE = ANIM_BASE + """
    @media (prefers-reduced-motion: reduce) {
      .k-anim { animation: none !important; }
    }
"""


def orbit_keyframes(name, rx, ry, base_theta, rot_deg=0.0, cx=C, cy=C, steps=48):
    """translate keyframes for a marker riding an ellipse starting at base_theta."""
    rot = math.radians(rot_deg)
    rows = []

    def pt(t):
        px0, py0 = rx * math.cos(t), ry * math.sin(t)
        return (cx + px0 * math.cos(rot) - py0 * math.sin(rot),
                cy + px0 * math.sin(rot) + py0 * math.cos(rot))

    bx, by = pt(math.radians(base_theta))
    for j in range(steps + 1):
        t = math.radians(base_theta) + 2 * math.pi * j / steps
        px, py = pt(t)
        rows.append('      %s%% { transform: translate(%spx, %spx); }'
                    % (f(100.0 * j / steps), f(px - bx), f(py - by)))
    return '@keyframes %s {\n%s\n    }' % (name, '\n'.join(rows))


# --------------------------------------------------- 1. armillary sphere
def armillary(p):
    defs, body, style = [], [], [RM_RULE]
    R = 300.0
    ERX, ERY = 284.0, 88.0
    TILT = -23.44

    # one key light for the whole instrument, plus three anisotropic metals
    defs.append(light_grad(p))
    defs.append(metal_grad(p, 'k-metal'))
    defs.append(metal_grad(p, 'k-metal-b', LIGHT_DEG - 34.0))
    defs.append(metal_grad(p, 'k-metal-c', LIGHT_DEG + 46.0))

    # construction square
    body.append('<rect x="100" y="100" width="600" height="600" fill="none" '
                'stroke="%s" stroke-width="0.8" stroke-dasharray="5 8"/>' % p['faint'])

    # letterpress echo: the bezel pressing into the paper (a cast stroke, never
    # a filled disc - the deco has to stay transparent line art)
    body.append(circle(R, p['shadow'], 7.0, cx=C + 3.2, cy=C + 4.2, op='0.07'))
    body.append(circle(R, p['gloss'], 0.9, cx=C - 1.4, cy=C - 1.8, op='0.5'))

    # outer bezel: real thickness, gradient body, key/shadow edges, metal grain
    body.append(band_ring(p, R, 8.5, 'k-metal'))
    body.append(lit_line(p, R + 4.6, 1.0))
    body.append(lit_line(p, R - 4.6, 1.0))
    body.append(stipple(p, C, C, R - 4.9, R + 4.9, 260, seed=13, size=0.55, op=0.17))
    # rivets around the bezel, each with a highlight facing the key light
    for i in range(24):
        a = math.radians(i * 15)
        rx, ry = C + R * math.cos(a), C + R * math.sin(a)
        face = 0.5 + 0.5 * math.cos(math.radians(i * 15) - math.radians(LIGHT_DEG))
        body.append(circle(2.5, p['coal'], 0, cx=rx, cy=ry, fill=p['coal'],
                           op=f(0.35 + 0.25 * (1 - face))))
        body.append(circle(1.1, p['gloss'], 0,
                           cx=rx - 0.9 * math.cos(math.radians(LIGHT_DEG)),
                           cy=ry - 0.9 * math.sin(math.radians(LIGHT_DEG)),
                           fill=p['gloss'], op=f(0.35 + 0.5 * face)))

    # graduation dial - STATIC, and light-aware: ticks facing the key light read
    # brighter, ticks on the shadow side fall away
    dial = []
    dial.append(lit_line(p, 286, 0.9))
    dial.append(circle(238, p['faint'], 0.9, dash='1 9'))
    for i in range(72):
        deg = i * 5
        a = math.radians(deg)
        face = 0.5 + 0.5 * math.cos(a - math.radians(LIGHT_DEG))
        if i % 18 == 0:
            ln, base, w = 24.0, p['accent'], 1.2
        elif i % 6 == 0:
            ln, base, w = 15.0, p['ink'], 1.0
        elif i % 2 == 0:
            ln, base, w = 9.0, p['soft'], 0.85
        else:
            ln, base, w = 5.0, p['faint'], 0.7
        col = p['gloss'] if (face > 0.78 and i % 6 == 0) else base
        c, s = math.cos(a), math.sin(a)
        dial.append(line(C + 286 * c, C + 286 * s, C + (286 - ln) * c,
                         C + (286 - ln) * s, col, w, op=f(0.42 + 0.5 * face)))
    body.append(''.join(dial))

    # three great-circle rings, each with body + thickness twin + lit edge
    body.append('<ellipse cx="400" cy="400" rx="%s" ry="%s" fill="none" '
                'stroke="url(#k-metal-b)" stroke-width="4.8" opacity="%s"/>'
                % (f(ERX), f(ERY), p['band']))
    body.append(ellipse(ERX, ERY, 'url(#k-light)', 2.4, op='0.55'))
    body.append(ellipse(ERX, ERY, p['ink'], 1.0))
    body.append(ellipse(ERX - 6.5, ERY - 6.5, p['coal'], 0.55, op='0.45'))
    body.append(ellipse(ERY, ERX, p['soft'], 0.9))
    body.append(ellipse(ERY, ERX, 'url(#k-light)', 2.0, op='0.45'))
    body.append(ellipse(ERY + 6.5, ERX + 6.5, p['faint'], 0.5))
    body.append('<g transform="rotate(%s 400 400)">'
                '<ellipse cx="400" cy="400" rx="%s" ry="%s" fill="none" '
                'stroke="url(#k-metal-c)" stroke-width="5.4" opacity="%s"/>'
                '<ellipse cx="400" cy="400" rx="%s" ry="%s" fill="none" '
                'stroke="url(#k-light)" stroke-width="2.4" opacity="0.5"/>'
                '<ellipse cx="400" cy="400" rx="%s" ry="%s" fill="none" stroke="%s" '
                'stroke-width="1.15"/>'
                '<ellipse cx="400" cy="400" rx="%s" ry="%s" fill="none" stroke="%s" '
                'stroke-width="0.55" opacity="0.5"/></g>'
                % (f(TILT), f(ERX), f(ERY), p['band'],
                   f(ERX), f(ERY), f(ERX), f(ERY), p['ink'],
                   f(ERX - 6), f(ERY - 6), p['coal']))

    # polar axis: twin walls for thickness, caps, hairline core
    axis = []
    for off in (-3.2, 3.2):
        axis.append(line(C + off, 104, C + off, 696, p['soft'], 0.75))
    axis.append(line(C, 86, C, 714, p['ink'], 0.85, dash='7 6'))
    for yy in (104.0, 696.0):
        axis.append(circle(9, p['ink'], 1.0, cy=yy))
        axis.append(circle(9, 'url(#k-light)', 1.8, cy=yy, op='0.5'))
        axis.append(circle(3, p['accent'] if yy == 104.0 else p['soft'], 0, cy=yy,
                           fill=p['accent'] if yy == 104.0 else p['soft']))
    axis.append(line(126, C, 674, C, p['soft'], 0.8, dash='6 8'))
    body.extend(axis)

    # the alidade: the only rotating part of the instrument itself, and it creeps
    style.append('''
    .k-alidade { animation-name: koyo-spin; animation-duration: 320s; }
    .k-sweep   { animation-name: koyo-spin; animation-duration: 52s; }
    .k-orb-glint-a { animation-name: k-orb-glint-a; animation-duration: 88s; }
    .k-orb-glint-b { animation-name: k-orb-glint-b; animation-duration: 64s; }
    .k-orb-planet  { animation-name: k-orb-planet; animation-duration: 96s; }
    .k-orb-moon    { animation-name: k-orb-moon; animation-duration: 27s; }
    .k-orb-node    { animation-name: k-orb-node; animation-duration: 132s; }
    @keyframes koyo-spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
''')
    style.append(orbit_keyframes('k-orb-glint-a', ERX, ERY, -12.0, rot_deg=TILT))
    style.append(orbit_keyframes('k-orb-glint-b', ERX, ERY, 150.0))
    style.append(orbit_keyframes('k-orb-planet', ERX, ERY, -34.0, rot_deg=TILT))
    style.append(orbit_keyframes('k-orb-moon', ERX, ERY, 126.0, rot_deg=TILT))
    style.append(orbit_keyframes('k-orb-node', ERX, ERY, 18.0))

    def epoint(rx, ry, th, rot):
        t = math.radians(th)
        rr = math.radians(rot)
        px0, py0 = rx * math.cos(t), ry * math.sin(t)
        return (C + px0 * math.cos(rr) - py0 * math.sin(rr),
                C + px0 * math.sin(rr) + py0 * math.cos(rr))

    # light gliding along the metal: a short gloss arc riding each ring
    gx, gy = epoint(ERX, ERY, -12.0, TILT)
    body.append('<g class="k-anim k-orb-glint-a">'
                '<path d="%s" fill="none" stroke="%s" stroke-width="1.7" '
                'opacity="0.8" transform="rotate(%s %s %s)"/>'
                '</g>' % (arc(gx, gy, 48, 175, 185), p['gloss'],
                          f(TILT), f(gx), f(gy)))
    hx, hy = epoint(ERX, ERY, 150.0, 0.0)
    body.append('<g class="k-anim k-orb-glint-b">'
                + path(arc(hx, hy, 52, -4, 4), p['gloss'], 1.5, op='0.6')
                + '</g>')

    # moving bodies, each with its own period
    px, py = epoint(ERX, ERY, -34.0, TILT)
    mk = []
    mk.append(circle(14, p['accent'], 0.9, cx=px, cy=py))
    mk.append(circle(6.5, p['accent'], 0, cx=px, cy=py, fill=p['accent']))
    mk.append(circle(2.2, p['gloss'], 0,
                     cx=px - 2.2 * math.cos(math.radians(LIGHT_DEG)),
                     cy=py - 2.2 * math.sin(math.radians(LIGHT_DEG)),
                     fill=p['gloss'], op='0.85'))
    mk.append(path(arc(px, py, 6.5, LIGHT_DEG - 40, LIGHT_DEG + 40),
                   p['gloss'], 1.4, op='0.6'))
    body.append('<g class="k-anim k-orb-planet">' + ''.join(mk) + '</g>')

    mx, my = epoint(ERX, ERY, 126.0, TILT)
    body.append('<g class="k-anim k-orb-moon">'
                + circle(3.6, p['ink'], 0, cx=mx, cy=my, fill=p['ink'], op='0.85')
                + circle(1.2, p['gloss'], 0, cx=mx - 1.2, cy=my - 1.2,
                         fill=p['gloss'], op='0.7')
                + '</g>')

    nx, ny = epoint(ERX, ERY, 18.0, 0.0)
    body.append('<g class="k-anim k-orb-node">'
                + circle(3.0, p['soft'], 0, cx=nx, cy=ny, fill=p['soft'])
                + circle(4.8, p['soft'], 0.7, cx=nx, cy=ny, op='0.7')
                + '</g>')

    # the alidade itself: hairline rule + counterweight + accent index
    hand = math.radians(-58.0)
    al = []
    al.append(line(C + 30 * math.cos(hand), C + 30 * math.sin(hand),
                   C + 196 * math.cos(hand), C + 196 * math.sin(hand),
                   p['ink'], 0.95))
    al.append(line(C + 30 * math.cos(hand), C + 30 * math.sin(hand),
                   C + 196 * math.cos(hand), C + 196 * math.sin(hand),
                   p['gloss'], 2.0, op='0.35'))
    al.append(circle(4.6, p['accent'], 0,
                     cx=C + 196 * math.cos(hand), cy=C + 196 * math.sin(hand),
                     fill=p['accent']))
    al.append(circle(7, p['soft'], 0.85, cx=C, cy=C))
    body.append('<g class="k-anim k-alidade">' + ''.join(al) + '</g>')

    # annotations stay put - they belong to the instrument, not the sky
    body.append(text(C, 62, 'N', p['accent'], size=12, ls=1.6))
    body.append(text(104, 728, '23.44', p['soft'], size=11, ls=1.4))
    return ''.join(defs), ''.join(style), body

# --------------------------------------------------- 2. seed of life
def bloom(p):
    defs, style, o = [], [RM_RULE], []
    r = 104.0
    defs.append(light_grad(p))
    centres = [(0.0, 0.0)] + [(r * math.cos(math.radians(i * 60)),
                               r * math.sin(math.radians(i * 60))) for i in range(6)]
    o.append(circle(2 * r, p['faint'], 0.9, dash='4 7', op='0.85'))
    o.append(polyline(reg(6, r), p['soft'], 0.9, close=True))
    for (x, y) in centres:
        ox, oy = C + x, C + y
        face = 0.5 + 0.5 * math.cos(math.atan2(y, x) - math.radians(LIGHT_DEG)) if x or y else 1.0
        o.append(circle(r, p['shadow'], 2.8, cx=ox + 2.4, cy=oy + 3.0, op='0.05'))
        o.append(circle(r, p['ink'], 1.05, cx=ox, cy=oy))
        o.append(circle(r, 'url(#k-light)', 2.3, cx=ox, cy=oy, op='0.42'))
        o.append(path(arc(ox, oy, r, LIGHT_DEG - 52, LIGHT_DEG + 52),
                      p['gloss'], 1.5, op=f(0.25 + 0.45 * face)))
    o.append(stipple(p, C, C, 34, 2 * r - 6, 170, seed=23, size=0.6, op=0.16))
    for i in range(6):
        a = math.radians(i * 60)
        o.append(circle(2.2, p['soft'], 0, cx=C + r * math.cos(a),
                        cy=C + r * math.sin(a), fill=p['soft'], op='0.7'))
    o.append(circle(30, p['soft'], 0.85))
    o.append(circle(30, 'url(#k-light)', 2.0, op='0.4'))
    o.append(circle(15, p['accent'], 1.0))
    o.append(path(arc(C, C, 15, LIGHT_DEG - 70, LIGHT_DEG + 40), p['gloss'], 1.3,
                  op='0.6'))
    o.append(circle(6, p['accent'], 0, fill=p['accent']))
    return ''.join(defs), ''.join(style), o

# --------------------------------------------------- 3. moon phases
def phases(p):
    defs, style, body = [], [MOON_CSS, RM_RULE], []
    N, R = 9, 42.0
    cx, cy, orb = 400.0, 486.0, 250.0
    yb = cy + R + 40.0            # sequence scale baseline
    PEN = 1.06                    # penumbra rides just outside the terminator

    pos = []
    for i in range(N):
        th = math.radians(180.0 - i * 22.5)
        pos.append((cx + orb * math.cos(th), cy - orb * math.sin(th)))

    body.append(path('M %s %s A %s %s 0 0 1 %s %s'
                     % (f(pos[0][0]), f(pos[0][1]), f(orb), f(orb),
                        f(pos[-1][0]), f(pos[-1][1])),
                     p['faint'], 0.8, dash='4 7'))

    for i, (x, y) in enumerate(pos):
        theta = math.pi * i / 8.0
        k = math.cos(theta)
        delay = -(T_MOON * i / 16.0)
        org = 'transform-origin:%spx %spx;animation-delay:%ss' % (f(x), f(y), f(delay))
        if abs(k) < 1e-9:
            op_b, op_w = 0, 0
        elif k > 0:
            op_b, op_w = 1, 0
        else:
            op_b, op_w = 0, 1
        hid = 'ph%d' % i
        half = 'M %s %s A %s %s 0 0 1 %s %s Z' % (f(x), f(y - R), f(R), f(R),
                                                  f(x), f(y + R))

        # ---- the soft shadow: Earth's penumbra trails the terminator ----
        defs.append('<mask id="%s" maskUnits="userSpaceOnUse" x="%s" y="%s" '
                    'width="%s" height="%s">' % (hid, f(x - R - 3), f(y - R - 3),
                                                 f(2 * R + 6), f(2 * R + 6)))
        defs.append('<path d="%s" fill="#ffffff" stroke="none"/>' % half)
        defs.append('<path class="k-anim k-core-b" style="%s;transform:scaleX(%s);'
                    'opacity:%d" d="%s" fill="#000000" stroke="none"/>'
                    % (org, f(k), op_b, half))
        defs.append('<path class="k-anim k-pen-b" style="%s;transform:scaleX(%s);'
                    'opacity:%d" d="%s" fill="#000000" fill-opacity="0.5" stroke="none"/>'
                    % (org, f(k * PEN), op_b, half))
        defs.append('<path class="k-anim k-core-w" style="%s;transform:scaleX(%s);'
                    'opacity:%d" d="%s" fill="#ffffff" stroke="none"/>'
                    % (org, f(k), op_w, half))
        defs.append('<path class="k-anim k-pen-w" style="%s;transform:scaleX(%s);'
                    'opacity:%d" d="%s" fill="#ffffff" fill-opacity="0.5" stroke="none"/>'
                    % (org, f(k * PEN), op_w, half))
        defs.append('</mask>')

        # ---- two gradients per moon: one directional, one for limb falloff --
        defs.append('<linearGradient id="phg%d" gradientUnits="userSpaceOnUse" '
                    'x1="%s" y1="%s" x2="%s" y2="%s">'
                    '<stop offset="0" stop-color="%s" stop-opacity="0.34"/>'
                    '<stop offset="0.45" stop-color="%s" stop-opacity="0.19"/>'
                    '<stop offset="0.82" stop-color="%s" stop-opacity="0.08"/>'
                    '<stop offset="1" stop-color="%s" stop-opacity="0.03"/>'
                    '</linearGradient>'
                    % (i, f(x - R), f(y), f(x + R), f(y), p['wash'], p['wash'],
                       p['wash'], p['gloss']))
        defs.append('<radialGradient id="phr%d" gradientUnits="userSpaceOnUse" '
                    'cx="%s" cy="%s" r="%s">'
                    '<stop offset="0.55" stop-color="%s" stop-opacity="0"/>'
                    '<stop offset="0.88" stop-color="%s" stop-opacity="0.07"/>'
                    '<stop offset="1" stop-color="%s" stop-opacity="0.2"/>'
                    '</radialGradient>'
                    % (i, f(x), f(y), f(R), p['wash'], p['wash'], p['coal']))

        # ---- unlit body: earthshine rim + a whisper of dust over the disc ---
        body.append(circle(R, p['soft'], 0.9, cx=x, cy=y, op='0.32'))
        body.append(circle(R, p['ink'], 1.15, cx=x, cy=y))
        body.append(circle(R, 'url(#k-light)', 2.2, cx=x, cy=y, op='0.4'))
        body.append(circle(R - 1.6, p['bounce'], 0.9, cx=x, cy=y, op='0.3'))

        # ---- everything lit lives under the phase mask ---------------------
        inner = []
        inner.append('<path d="%s" fill="url(#phg%d)"/>' % (half, i))
        hatch = []
        xx = x - R + 3
        while xx <= x + R - 3:
            hatch.append('<line x1="%s" y1="%s" x2="%s" y2="%s"/>'
                         % (f(xx), f(y - R + 1), f(xx), f(y + R - 1)))
            xx += 6.0
        inner.append('<g fill="none" stroke="%s" stroke-width="0.6" opacity="0.3">%s</g>'
                     % (p['ink'], ''.join(hatch)))
        g = lcg(101 + i * 37)
        tex = []
        for n in range(5):
            rr = 0.5 + g.__next__() * 0.5
            aa = g.__next__() * 2 * math.pi
            dd = 6.0 + g.__next__() * (R - 15.0)
            tx, ty = x + dd * math.cos(aa), y + dd * math.sin(aa)
            tex.append(circle(2.4 + 3.4 * rr, p['coal'], 0.6, cx=tx, cy=ty, op='0.55'))
            tex.append(path(arc(tx, ty, 2.4 + 3.4 * rr, LIGHT_DEG - 52, LIGHT_DEG + 24),
                            p['gloss'], 0.7, op='0.55'))
        for n in range(2):
            aa = g.__next__() * 2 * math.pi
            dd = 8.0 + g.__next__() * (R - 20.0)
            tx, ty = x + dd * math.cos(aa), y + dd * math.sin(aa)
            tex.append(path(arc(tx, ty, 6 + 7 * rr, -70, 70), p['soft'], 0.62, op='0.5'))
        inner.append('<g fill="none">%s</g>' % ''.join(tex))
        inner.append('<path d="%s" fill="url(#phr%d)"/>'
                     % ('M %s %s A %s %s 0 0 1 %s %s A %s %s 0 0 1 %s %s Z'
                        % (f(x), f(y - R), f(R), f(R), f(x), f(y + R),
                           f(R), f(R), f(x), f(y - R)), i))
        inner.append(path(arc(x, y, R - 2.6, LIGHT_DEG - 54, LIGHT_DEG + 54),
                          p['gloss'], 1.8, op='0.6'))
        body.append('<g mask="url(#%s)">%s</g>' % (hid, ''.join(inner)))

        # ---- terminator: hard core line + the penumbra behind it -----------
        tpath = 'M %s %s A %s %s 0 0 1 %s %s' % (f(x), f(y - R), f(R), f(R),
                                                 f(x), f(y + R))
        body.append('<path class="k-anim k-pen-t" style="%s;transform:scaleX(%s)" '
                    'd="%s" fill="none" stroke="%s" stroke-width="1.9" opacity="0.22"/>'
                    % (org, f(k * PEN), tpath, p['ink']))
        body.append('<path class="k-anim k-term" style="%s;transform:scaleX(%s)" '
                    'd="%s" fill="none" stroke="%s" stroke-width="0.9"/>'
                    % (org, f(k), tpath, p['soft']))

        # ---- sequence scale -----------------------------------------------
        body.append(line(x, y + R + 7, x, yb, p['faint'], 0.7, dash='2 7'))
        body.append(line(x, yb, x, yb + 11, p['soft'], 0.85))
        if i in (0, 4, 8):
            body.append(text(x, yb + 28, ('NEW', 'HALF', 'FULL')[i // 4],
                             p['soft'], size=9.5, ls=2.4))

    body.append(line(pos[0][0] - 22, yb, pos[-1][0] + 22, yb, p['soft'], 0.9,
                     dash='7 6'))
    for i in range(N - 1):
        mx = (pos[i][0] + pos[i + 1][0]) / 2.0
        body.append(line(mx, pos[i][1], mx, yb, p['faint'], 0.6, dash='2 9'))
        body.append(line(mx, yb, mx, yb + 5, p['soft'], 0.7))
    return ''.join(defs), ''.join(style), body

# --------------------------------------------------- 4. interference rose
def resonance(p):
    o = []
    RIM = 330.0
    o.append(circle(RIM, p['faint'], 0.9, dash='4 6'))
    rings = 15
    for i in range(rings):
        base = 34.0 + i * 17.8
        amp = 3.0 + i * 1.1
        phase = i * 0.235
        pts = []
        for d in range(0, 361, 3):
            t = math.radians(d)
            rr = (base + amp * math.sin(3 * t + phase)
                  + amp * 0.34 * math.sin(7 * t - phase * 1.7))
            pts.append((C + rr * math.cos(t), C + rr * math.sin(t)))
        o.append(polyline(pts, p['ink'], 0.75 + i * 0.032, close=True,
                          op='0.9' if i % 2 else '0.55'))
    for i in range(72):
        a = math.radians(i * 5)
        ln = 12.0 if i % 6 == 0 else 5.0
        col = p['accent'] if i % 18 == 0 else p['soft']
        o.append(line(C + RIM * math.cos(a), C + RIM * math.sin(a),
                      C + (RIM + ln) * math.cos(a), C + (RIM + ln) * math.sin(a),
                      col, 0.8))
    o.append(circle(19, p['soft'], 0.85))
    o.append(circle(11, p['accent'], 1.0))
    o.append(circle(4.5, p['accent'], 0, fill=p['accent']))
    return '', RM_RULE, o


# --------------------------------------------------- 5. rose window
def rosette(p):
    defs, style, o = [], [RM_RULE], []
    defs.append(light_grad(p))
    n = 12
    half = math.pi / n
    r_base, r_tip = 96.0, 250.0
    o.append(circle(292, p['faint'], 0.9, dash='4 7', op='0.8'))
    # frame: cast echo, lit wire, key edge, shadow edge
    o.append(circle(284, p['shadow'], 4.5, cx=C + 2.2, cy=C + 2.8, op='0.05'))
    o.append(circle(284, p['soft'], 0.85))
    o.append(circle(284, 'url(#k-light)', 2.1, op='0.45'))
    o.append(circle(276, p['ink'], 1.05))
    o.append(path(arc(C, C, 280, LIGHT_DEG - 86, LIGHT_DEG + 86), p['gloss'], 1.6,
                  op='0.6'))
    o.append(path(arc(C, C, 276, LIGHT_DEG + 94, LIGHT_DEG + 266), p['coal'], 1.1,
                  op='0.45'))
    o.append(stipple(p, C, C, 274, 292, 220, seed=31, size=0.55, op='0.16'))
    for i in range(n):
        a = math.radians(-90 + i * 360.0 / n)
        face = 0.5 + 0.5 * math.cos(a - math.radians(LIGHT_DEG))
        am = a + half
        o.append(line(C + r_base * math.cos(am), C + r_base * math.sin(am),
                      C + 276 * math.cos(am), C + 276 * math.sin(am),
                      p['soft'], 0.7, dash='3 6', op=f(0.3 + 0.35 * face)))
        pL = (C + r_base * math.cos(a - half), C + r_base * math.sin(a - half))
        pR = (C + r_base * math.cos(a + half), C + r_base * math.sin(a + half))
        tip = (C + r_tip * math.cos(a), C + r_tip * math.sin(a))
        cL = (C + 168 * math.cos(a - half * 1.75), C + 168 * math.sin(a - half * 1.75))
        cR = (C + 168 * math.cos(a + half * 1.75), C + 168 * math.sin(a + half * 1.75))
        d = ('M %s %s Q %s %s %s %s Q %s %s %s %s Z'
             % (f(pL[0]), f(pL[1]), f(cL[0]), f(cL[1]),
                f(tip[0]), f(tip[1]), f(cR[0]), f(cR[1]), f(pR[0]), f(pR[1])))
        o.append(path(d, p['ink'], 1.0))
        o.append(path(d, 'url(#k-light)', 2.4, op=f(0.2 + 0.35 * face)))
    o.append(circle(r_base, p['soft'], 0.9))
    o.append(circle(r_base, 'url(#k-light)', 2.0, op='0.4'))
    o.append(circle(46, p['soft'], 0.85, dash='3 5'))
    o.append(circle(14, p['accent'], 1.0))
    o.append(path(arc(C, C, 14, LIGHT_DEG - 80, LIGHT_DEG + 30), p['gloss'], 1.2,
                  op='0.55'))
    o.append(circle(5, p['accent'], 0, fill=p['accent']))
    return ''.join(defs), ''.join(style), o


# --------------------------------------------------- 6. orthographic globe
def atlas(p):
    """A globe on true orthographic projection: hidden lines are removed, the
    limb is shaded, one great-circle route crosses it."""
    defs, style, o = [], [RM_RULE], []
    R = 262.0
    defs.append(light_grad(p))
    defs.append(metal_grad(p, 'k-metal'))
    TH = math.radians(22.0)     # viewing elevation

    def proj(lat, lon):
        la, lo = math.radians(lat), math.radians(lon)
        x = math.cos(la) * math.sin(lo)
        ys = math.sin(la)
        y = -(ys * math.cos(TH) - math.cos(la) * math.sin(TH) * math.cos(lo))
        z = math.cos(la) * math.cos(TH) * math.cos(lo) + ys * math.sin(TH)
        return (C + R * x, C + R * y, z)

    def curve(kind, fixed, col, w, op=None, dash=None):
        segs, cur, zprev = [], [], None
        rng = [(-84 + i * 3.0) for i in range(57)] if kind == 'mer' else \
              [(-180 + i * 3.0) for i in range(121)]
        for v in rng:
            pt = proj(v, fixed) if kind == 'mer' else proj(fixed, v)
            if pt[2] > 0:
                if not cur:
                    cur = [pt]
                else:
                    cur.append(pt)
            else:
                if len(cur) > 2:
                    segs.append(cur)
                cur = []
        if len(cur) > 2:
            segs.append(cur)
        for s in segs:
            o.append(polyline([(pt[0], pt[1]) for pt in s], col, w, dash=dash, op=op))

    # limb: outer wire + an inner coal ring for volume + key-light crescent
    o.append(circle(R, p['shadow'], 6.0, cx=C + 2.6, cy=C + 3.4, op='0.05'))
    o.append(circle(R - 7, p['coal'], 0.9, op='0.35'))
    o.append(circle(R, p['ink'], 1.15))
    o.append(circle(R, 'url(#k-light)', 2.8, op='0.5'))
    o.append(path(arc(C, C, R, LIGHT_DEG - 74, LIGHT_DEG + 74), p['gloss'], 2.0,
                  op='0.7'))
    o.append(stipple(p, C, C, R - 26, R - 3, 260, seed=41, size=0.55, op='0.14'))

    for lat in (-60, -30, 0, 30, 60):
        curve('par', lat, p['soft'], 0.8 if lat else 1.15,
              op='0.75' if lat else None)
    for lon in range(-75, 90, 15):
        curve('mer', lon, p['ink'], 0.75, op='0.55')

    # one great-circle route, accent, with a node at each end
    a0, a1 = (51.5, -0.1), (-33.9, 18.4)   # a route on the visible hemisphere
    route = []
    steps = 64
    la0, lo0 = math.radians(a0[0]), math.radians(a0[1])
    la1, lo1 = math.radians(a1[0]), math.radians(a1[1])
    dd = math.acos(min(1.0, max(-1.0, math.sin(la0) * math.sin(la1)
                                + math.cos(la0) * math.cos(la1) * math.cos(lo1 - lo0))))
    for i in range(steps + 1):
        tt = i / float(steps)
        A = math.sin((1 - tt) * dd) / math.sin(dd)
        B = math.sin(tt * dd) / math.sin(dd)
        x = A * math.cos(la0) * math.cos(lo0) + B * math.cos(la1) * math.cos(lo1)
        y = A * math.cos(la0) * math.sin(lo0) + B * math.cos(la1) * math.sin(lo1)
        z = A * math.sin(la0) + B * math.sin(la1)
        lat = math.degrees(math.asin(z))
        lon = math.degrees(math.atan2(y, x))
        pt = proj(lat, lon)
        if pt[2] > 0:
            route.append(pt)
    if len(route) > 3:
        o.append(polyline([(pt[0], pt[1]) for pt in route], p['accent'], 1.4, dash=None))
        o.append(polyline([(pt[0], pt[1]) for pt in route], p['gloss'], 2.6, op='0.4'))
    for a in (a0, a1):
        pt = proj(a[0], a[1])
        if pt[2] > 0:
            o.append(circle(4.6, p['accent'], 0.9, cx=pt[0], cy=pt[1]))
            o.append(circle(2.2, p['accent'], 0, cx=pt[0], cy=pt[1],
                            fill=p['accent']))
    o.append(text(C, C + R + 34, 'ORTHOGRAPHIC', p['soft'], size=10, ls=3.4))
    return ''.join(defs), ''.join(style), o

DESIGNS = [
    ('deco_armillary', armillary),
    ('deco_bloom', bloom),
    ('deco_phases', phases),
    ('deco_resonance', resonance),
    ('deco_rosette', rosette),
    ('deco_atlas', atlas),
]


def build(name, fn, p):
    defs, style, body = fn(p)
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" '
            'width="%d" height="%d">\n'
            '  %s\n'
            '  <defs>%s</defs>\n'
            '  <style>%s</style>\n'
            '  <g fill="none" stroke-linecap="round" stroke-linejoin="round">\n'
            '  %s\n'
            '  </g>\n'
            '</svg>\n') % (S, S, S, S, MARK, defs, style, '\n  '.join(body))


def strip_motion(src):
    """Baked still frame: drop every trace of motion.

    Needed because Chromium does not propagate prefers-reduced-motion into an
    SVG loaded through <img> (verified: the internal media query only fires for
    inlined SVG), so the page must be able to pick a static file instead.
    """
    import re
    out = re.sub(r'\n\s*<style>.*?</style>', '', src, flags=re.S)
    out = re.sub(r'\s*style="animation-duration:[^"]*"', '', out)
    out = re.sub(r'\s*class="[^"]*k-anim[^"]*"', '', out)
    out = re.sub(r';animation-delay:-?[\d.]+s', '', out)
    assert 'animation' not in out, 'motion leaked into the still frame'
    return out


def write(name, body):
    dest = os.path.join(OUT, name)
    if os.path.exists(dest):
        try:
            head = open(dest, 'r', encoding='utf-8').read(400)
        except Exception:
            head = ''
        if MARK not in head:
            print('  SKIP (protected, not generated by this tool): %s' % name)
            return False
    open(dest, 'w', encoding='utf-8', newline='\n').write(body)
    return True


def selftest():
    """Numeric guards - these shapes are generated without being looked at."""
    # seed-of-life: seven circles of equal radius, all mutually overlapping
    r = 104.0
    centres = [(0.0, 0.0)] + [(r * math.cos(math.radians(i * 60)),
                               r * math.sin(math.radians(i * 60))) for i in range(6)]
    assert len(centres) == 7
    # rose window: petals must tile the annulus without overlapping neighbours
    assert abs(math.pi / 12 * 12 - math.pi) < 1e-9
    # moon cycle: illumination must rise monotonically, hitting the exact quarter
    vals = [0.5 * (1 - math.cos(math.pi * i / 8.0)) for i in range(9)]
    assert vals == sorted(vals) and vals[0] == 0.0 and abs(vals[-1] - 1.0) < 1e-9
    assert abs(vals[4] - 0.5) < 1e-9, 'moon 4 must be the exact half'
    assert abs(vals[2] - 0.5 * (1 - math.cos(math.pi / 4))) < 1e-9
    # resonance rose must stay inside its rim
    peak = 0.0
    for i in range(15):
        base, amp, phase = 34.0 + i * 17.8, 3.0 + i * 1.1, i * 0.235
        for d in range(0, 361):
            t = math.radians(d)
            peak = max(peak, base + amp * math.sin(3 * t + phase)
                       + amp * 0.34 * math.sin(7 * t - phase * 1.7))
    assert peak < 320.0, 'rose peak %.1f overflows the rim' % peak
    # armillary: ring stack must nest without colliding with the bezel band
    assert 284.0 - 6.0 > 210.0, 'horizontal ring must clear the inner index ring'
    assert 88.0 + 6.0 < 300.0 - 7.0, 'meridian ring must stay inside the bezel'
    print('  selftest ok: 7 seed circles, quarter moon exact, rose peak %.1f/330' % peak)


MOTION_AUDIT = {}


def main():
    selftest()
    made = 0
    for base, fn in DESIGNS:
        light = build(base, fn, LIGHT)
        dark = build(base, fn, DARK)
        light_still = strip_motion(light)
        dark_still = strip_motion(dark)
        moving = 'class="k-anim' in light        # nothing to bake otherwise
        names = [base + '.svg', base + '_dark.svg']
        srcs = [light, dark]
        if moving:
            names += [base + '_still.svg', base + '_still_dark.svg']
            srcs += [light_still, dark_still]
        for src in srcs:
            ET.fromstring(src)
        for nm, src in zip(names, srcs):
            if write(nm, src):
                made += 1
        MOTION_AUDIT[base] = (light.count('k-anim'), len(light.split('@keyframes')) - 1)
        if moving:
            print('  wrote %-22s %6d B  + dark %6d B  + still %6d/%d B  anim nodes %-2d'
                  % (base + '.svg', len(light), len(dark), len(light_still),
                     len(dark_still), light.count('k-anim') - 2))
        else:
            print('  wrote %-22s %6d B  + dark %6d B            (static)'
                  % (base + '.svg', len(light), len(dark)))
    print('done: %d files in %s' % (made, OUT))


if __name__ == '__main__':
    main()
