/* test-t2s.js — smoke-test the runtime 繁→简 converter inside i18n.js */
'use strict';
const fs = require('fs');
const path = require('path');

/* minimal browser stubs so i18n.js can boot in Node */
const store = {};
global.localStorage = {
  getItem: (k) => (k in store ? store[k] : null),
  setItem: (k, v) => { store[k] = String(v); },
};
global.document = {
  documentElement: {},
  addEventListener: () => {},
  querySelectorAll: () => [],
  body: null,
  title: '',
};
global.window = global;
global.location = { reload: () => {} };

const src = fs.readFileSync(path.join(__dirname, '..', 'docs', 'js', 'i18n.js'), 'utf8');
eval(src);

const I18N = global.I18N;
/* authoritative cases generated by tools/gen-t2s-cases.py (Python zhconv) */
const cases = JSON.parse(
  fs.readFileSync(path.join(__dirname, '_t2s_cases.json'), 'utf8')
);

let fails = 0;
for (const [input, want] of cases) {
  const got = I18N.t2s(input);
  if (got !== want) {
    fails++;
    console.log('MISMATCH');
    console.log('  in:   ' + input);
    console.log('  want: ' + want);
    console.log('  got:  ' + got);
  }
}

/* lang plumbing */
store['koyome_lang'] = 'zhcn';
if (I18N.lang !== 'en') { fails++; console.log('lang getter wrong before reload (module cached):', I18N.lang); }
console.log(fails === 0 ? 'ALL T2S CASES PASS (' + cases.length + ')' : fails + ' FAILURES');
process.exit(fails === 0 ? 0 : 1);
